library(GenomicRanges)
library(ScRNAClone)
library(vcfR)

# We are now going to generate SNVss and CNV in a format recognized by our software.
# For this, we are going to use vcfR package.
# For comparison to PhyloWGS, we will need to ensure that the SNVs that we generate
# are matched in the input generated for PhyloWGS.
# Therefore, we must complete the step to generate input for PhyloWGS before running this script.

chrs <- c(1:22, "X", "Y")
nucleotides <- c("A","C","G","T")
vcf_file <- "/Users/seonghwanjun/data/cell-line/bulk/A90554A/somatic.snvs.vcf.gz"
pgs_ssm_file <- "/Users/seonghwanjun/data/cell-line/bulk/A90554A/ssm_data.txt"
titan_cna_file <- "/Users/seonghwanjun/data/cell-line/bulk/A90554A/hmm/optimalClusterSolution/tumor_sample_1_cluster1.segs.txt"
output_file <- "/Users/seonghwanjun/data/cell-line/bulk/A90554A/snv.txt"

# Load the raw VCF file, but this time as a vcf object.
vcf <- read.vcfR(vcf_file)
fix <- getFIX(vcf)
fix.df <- data.frame(fix)
fix.df$POS <- as.numeric(as.character(fix.df$POS))
fix.df$CHROM <- as.character(fix.df$CHROM)

# Load input file generated by PhyloWGS.
library(plyr)
pgs <- read.table(pgs_ssm_file, header=T, as.is=TRUE)
pgs.coord <- ldply(strsplit(pgs$gene, "_"), function(row) {
    return(data.frame(CHR=row[1], POS=row[2]))
});
detach("package:plyr", unload = TRUE)
pgs.coord$CHR <- as.character(pgs.coord$CHR)
pgs.coord$POS <- as.numeric(pgs.coord$POS)

# Extract only the relevant entries.
vcf.gr <- ConstructGranges(fix.df$CHROM, fix.df$POS, width = 0)
pgs.gr <- ConstructGranges(pgs.coord$CHR, pgs.coord$POS, width = 0)
ret <- findOverlaps(vcf.gr, pgs.gr)

vcf.exon <- vcf[ret@from]
vcf.exon.fix.df <- data.frame(getFIX(vcf.exon))
dim(vcf.exon.fix.df)[1] == dim(pgs)[1]

vcf.exon.fix.df$b <- pgs$d - pgs$a
vcf.exon.fix.df$d <- pgs$d

# Let's re-arrange the columns and remove unnecessary columns.
n_snvs <- dim(vcf.exon.fix.df)[1]
ids <- paste("s", 0:(n_snvs-1), sep="")
mean(ids == pgs$id)

snv <- data.frame(ID=ids, CHR=vcf.exon.fix.df$CHROM, POS=vcf.exon.fix.df$POS,
                  REF=vcf.exon.fix.df$REF, ALT=vcf.exon.fix.df$ALT,
                  b=vcf.exon.fix.df$b, d=vcf.exon.fix.df$d)
snv$POS <- as.numeric(as.character(snv$POS))
head(snv)

# Generate CNV data.
cnv <- read.table(titan_cna_file, header=T, as.is = TRUE)
# TitanCNA output seems to be half open intervals , so we +1 for width.
cnv.gr <- ConstructGranges(chr = cnv$Chromosome, start = cnv$Start_Position.bp., width = cnv$End_Position.bp. - cnv$Start_Position.bp. + 1)
snv.gr <- ConstructGranges(chr = as.character(snv$CHR), start = snv$POS, width = 0)
ret <- findOverlaps(snv.gr, cnv.gr)
snv$MajorCN <- rep(1, n_snvs)
snv$MinorCN <- rep(1, n_snvs)
snv$MajorCN[ret@from] <- cnv$Corrected_MajorCN[ret@to]
snv$MinorCN[ret@from] <- cnv$Corrected_MinorCN[ret@to]

write.table(snv, output_file, quote = FALSE, col.names = TRUE, row.names = FALSE, sep="\t")
head(snv)

