# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ReadParentVector <- function(file_path, mutation_count) {
    .Call(`_ScRNACloneEvaluation_ReadParentVector`, file_path, mutation_count)
}

#' @export
GetChains <- function(parent_vector) {
    .Call(`_ScRNACloneEvaluation_GetChains`, parent_vector)
}

