# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_VAFclusterEM_rcpp_hello_world', PACKAGE = 'VAFclusterEM')
}

ReadParentVector <- function(file_path, mutation_count) {
    .Call('_VAFclusterEM_ReadParentVector', PACKAGE = 'VAFclusterEM', file_path, mutation_count)
}

GetChains <- function(parent_vector) {
    .Call('_VAFclusterEM_GetChains', PACKAGE = 'VAFclusterEM', parent_vector)
}

